name: Build and Create APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '18'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Create artifacts directory
        run: mkdir -p artifacts

      - name: Move APK to artifacts directory
        run: mv app/build/outputs/apk/debug/app-debug.apk artifacts/

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-debug
          path: artifacts/app-debug.apk